version: '3.2'

services:
  db:
    build: ./db
    container_name: 'flask_db'
    expose:
      - "3306"
    env_file:
      - ./env/db.env
    volumes:
      - ../db/database:/var/lib/mysql
      - ../db/init:/docker-entrypoint-initdb.d
  web:
    build: ./web
    container_name: 'flask_web'
    ports:
      - 5000:5000
    stdin_open: true
    tty: true
    volumes:
      - ../web:/home/user1/dev
      